yarnPath: .yarn/releases/yarn-4.2.1.cjs

nodeLinker: node-modules
enableGlobalCache: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
